### ISSUE TITLE
Array2XML converter

### ISSUE THREAD

**Issue by dwenzel** [dwenzel/t3import_export#1]
Hi @brannow,
here is a sample implementation: 
http://www.lalit.org/lab/convert-php-array-to-xml-with-attributes/
http://ppfeufer.de/php-einmal-xml-to-array-und-zurueck-bitte/
I would not copy this, but the array structure conventions seem quite sensible.

**Comment by brannow** [comment]
convert an Array with the correct meta information into an xml (cdata, attribute, etc...) its easy.
Generate the correct array structure like as in http://ppfeufer.de/php-einmal-xml-to-array-und-zurueck-bitte/ is way to complex for typoscript 

a fair compromise would be a simple structure mapping as PreProcessor like:

```
$record = array(
    'performances' => array(
        'someField' => '123',
        'otherFieldName' => 'otherXMLNode'
    )
);
performances {
    mapTo = schedule
    children {
        someField {
             @attribute = someAttributeName
        }
    }
}
```

is maybe this 

```
<schedule someAttributeName="123">
    <otherFieldName>otherXMLNode</otherFieldName>
</schedule>
```

the value field is to set static data to a non existing array element.
without the value field, assumed 'someField' is an existing array element, it used the array value

**Comment by brannow** [comment]
finished in b00abf1
