### ISSUE TITLE
It is not possible to use a different DB connections in release/0.6.2

### ISSUE THREAD

**Issue by vladimirfalconpiva** [dwenzel/t3import_export#3]
It is not possible to use a different DB connection. here  CPSIT\T3importExport\Persistence\DataSourceDB\getDatabase() is the variable $this->database allays an instance of DatabaseConnection. See DatabaseTrait __construct().

Source identifier is because of this not working any longer.

**Comment by dwenzel** [comment]
You are right, sorry. This issue has been introduced when the class has been refactored to use the DatabaseTrait.
The intention was to have the local TYPO3 DB as a default for DataSourceDB too.
As a quick fix you could overwrite the constructor from trait with an empty constructor.

**Comment by dwenzel** [comment]
should be fixed with version 0.6.3.
@vladimirfalconpiva can you please confirm?

**Comment by vladimirfalconpiva** [comment]
jop
