### ISSUE TITLE
More configuration examples

### ISSUE THREAD

**Issue by motordigital** [dwenzel/t3import_export#7]
Hello,

your extension seems to be quite flexible through a high abstraction level. I use it within a heavy data import process. As working with the extensions, it is sometime a little hard to find out the configuration by code analysis. 

What about adding more configuration examples? I could also supply some as I did a hand full in the last days (contact: hempel@motor.berlin).

Great work,
Jan

**Comment by metaxos** [comment]
Hi Jan. Could you share them? I'm looking to export some data of an extension. 

Thank you.

**Comment by dwenzel** [comment]
Hi @metaxos,
I'm aware that there is still a lot of documentation missing.
Could you please describe your goals? (Export target, export source and structure). I could provide some hints then.

cheers 
Dirk

**Comment by metaxos** [comment]
Hr Dirk

Thank you. I'm looking for a generic way to export some data of own extensions every X time. The target  is to send specific data from one TYPO3 to another via the exported file. Could I get the latest 3 news with category "blah" and export them to a file and then re-import this data on another system?

Kind regards
Jacques

**Comment by motordigital** [comment]
Hello @metaxos, I will add some more examples and documentation step by step in the next weeks.

**Comment by dwenzel** [comment]
Hi @metaxos.
That's possible, allthough currently one required component is still missing (There is a finisher for downloading a file, but not yet for storing it to a folder. I plan to implement such a finisher anyway...).

I would suggest a different but much simpler way:
* register your source database in the target system using the DatabaseConnectionService
* write an import configuration with DataSourceDB (which uses the registered database)
* optionally pre-process the records from this source
* use the DataTargetDB to store them
* use a scheduler task to run your import regularly

If the structure of your data is complex and/or many tables are involved on either side, the DataTargetDB might not be the best choice. It is designed to update only one table and you would have to split your import into multiple tasks. 
If an Extbase Model is available, the DataTargetRepository might be a better choice (I recently added some documentation for this component). This component creates an Domain Object from a nested array and persists it via its repository method. 

If the first case is an option for you, I would provide some example within the next few days.

cheers
Dirk

**Comment by dwenzel** [comment]
Hi Jan, can this issue be closed. 
Do you still miss any examples, do you plan another pull request?
